version: 2.1
jobs:
  test:
    machine:
      image: 'ubuntu-2004:202010-01'
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

workflows:
  install_and_test:
    jobs:
      - example
